const mutations=[
  {name:"Normal / Base",value:1,status:"confirmed"},{name:"Radiant",value:1.25,status:"confirmed",base:true},{name:"Sunburst",value:1.35,status:"confirmed"},
  {name:"Blazing",value:1.4,status:"confirmed",base:true},{name:"Corrupted",value:1.65,status:"confirmed",base:true},{name:"Iceborn",value:1.8,status:"confirmed",base:true},
  {name:"Moonlit",value:2,status:"confirmed",base:true},{name:"Aurora",value:2,status:"confirmed"},{name:"Void",value:2.1,status:"confirmed"},
  {name:"Summer",value:2.25,status:"confirmed"},{name:"Abyssal",value:2.3,status:"confirmed",base:true},{name:"Candy",value:2.6,status:"confirmed",base:true},
  {name:"Cherished",value:2.9,status:"confirmed"},{name:"Crimson",value:3,status:"confirmed",base:true},{name:"Glitched",value:3.1,status:"confirmed"},
  {name:"Velvet",value:3.2,status:"confirmed"},{name:"Pixelated",value:3.4,status:"confirmed"},{name:"Blossom",value:4,status:"confirmed"},
  {name:"Eclipse",value:3,status:"confirmed"},{name:"Cosmic",value:3.8,status:"confirmed"},{name:"Hollow",value:4.4,status:"confirmed"},{name:"Starlight",value:5,status:"confirmed"}
];
const rarities=[
  ["Common",.75],["Uncommon",1.25],["Rare",1.8],["Epic",9],["Legendary",11],["Mythic",12],["Ethereal",14],["Secret",17],
  ["Oblivion",24],["Eternal",28],["Transcendent",34],["Infinity",250],["Apex",460],["Event",475],["Fansign",480],["Vacation",490],
  ["Concept",500],["Performance",520],["Visual",530],["Iconic",545],["Fashion",555],["Harmony",575],["Munch",595],["Cutesy",610],["Pets",650],
  ["Airport",660],["Maknae",665],["Formal",675],["Plushie",685],["Vocal",770]
];
const observedWeights={
  Ethereal:[46.92,59.97,8],Infinity:[99.13,106.25,3],Apex:[99.55,119.67,26],Event:[95.00,124.56,35],
  Fansign:[100.00,121.09,17],Vacation:[110.89,122.99,7],Concept:[100.80,124.60,34],Performance:[110.09,129.63,56],Visual:[110.54,129.16,16],
  Fashion:[120.04,139.96,34],Iconic:[111.18,129.83,41],Harmony:[122.19,134.44,23],
  Munch:[119.47,144.96,46],Cutesy:[128.19,144.98,38],Pets:[133.31,144.66,29],Maknae:[130.09,144.46,9],Formal:[127.93,144.46,11],
  Plushie:[146.37,149.99,9],Airport:[129.21,144.38,2],Vocal:[150.66,162.78,2]
};
const packPool=[
  {pack:"Common",idol:"Jiwoong",group:"ZEROBASEONE",rarity:"Common"},
  {pack:"Common",idol:"Riku",group:"NCT WISH",rarity:"Common"},
  {pack:"Common",idol:"Sehun",group:"EXO",rarity:"Common"},
  {pack:"Common",idol:"Mingyu",group:"SEVENTEEN",rarity:"Common"},
  {pack:"Common",idol:"Ruka",group:"BABYMONSTER",rarity:"Common"},
  {pack:"Common",idol:"Lisa",group:"BLACKPINK",rarity:"Common"},
  {pack:"Common",idol:"Chaeyoung",group:"TWICE",rarity:"Common"},
  {pack:"Common",idol:"Lia",group:"ITZY",rarity:"Common"},
  {pack:"Common",idol:"Jiheon",group:"fromis_9",rarity:"Common"},
  {pack:"Common",idol:"Sophia",group:"KATSEYE",rarity:"Common"},
  {pack:"Common",idol:"Fuma",group:"&TEAM",rarity:"Common"},
  {pack:"Common",idol:"Sungho",group:"BOYNEXTDOOR",rarity:"Common"},
  {pack:"Uncommon",idol:"Jiung",group:"P1Harmony",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"J",group:"STAYC",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Jinu",group:"WINNER",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Daniela",group:"KATSEYE",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Rose",group:"BLACKPINK",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Saerom",group:"fromis_9",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Jeongyeon",group:"TWICE",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Rora",group:"BABYMONSTER",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Belle",group:"KISS OF LIFE",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"EJ",group:"&TEAM",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Eunseo",group:"WJSN",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Riwoo",group:"BOYNEXTDOOR",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Matthew",group:"ZEROBASEONE",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Xiumin",group:"EXO",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"The8",group:"SEVENTEEN",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Winwin",group:"NCT / WayV",rarity:"Uncommon"},
  {pack:"Uncommon",idol:"Taeyang",group:"BIGBANG",rarity:"Uncommon"},
  {pack:"Rare",idol:"Chaeryeong",group:"ITZY",rarity:"Rare"},
  {pack:"Rare",idol:"Xiaojun",group:"WayV",rarity:"Rare"},
  {pack:"Rare",idol:"K",group:"&TEAM",rarity:"Rare"},
  {pack:"Rare",idol:"Jake",group:"ENHYPEN",rarity:"Rare"},
  {pack:"Rare",idol:"Taemin",group:"SHINee",rarity:"Rare"},
  {pack:"Rare",idol:"Soul",group:"P1Harmony",rarity:"Rare"},
  {pack:"Rare",idol:"Lara",group:"KATSEYE",rarity:"Rare"},
  {pack:"Rare",idol:"Jisoo",group:"BLACKPINK",rarity:"Rare"},
  {pack:"Rare",idol:"Yeosang",group:"ATEEZ",rarity:"Rare"},
  {pack:"Rare",idol:"Haneul",group:"KISS OF LIFE",rarity:"Rare"},
  {pack:"Rare",idol:"Nagyung",group:"fromis_9",rarity:"Rare"},
  {pack:"Rare",idol:"James",group:"CORTIS",rarity:"Rare"},
  {pack:"Rare",idol:"Taerae",group:"ZEROBASEONE",rarity:"Rare"},
  {pack:"Rare",idol:"RM",group:"BTS",rarity:"Rare"},
  {pack:"Rare",idol:"Leehan",group:"BOYNEXTDOOR",rarity:"Rare"},
  {pack:"Rare",idol:"Dahyun",group:"TWICE",rarity:"Rare"},
  {pack:"Rare",idol:"Jeonghan",group:"SEVENTEEN",rarity:"Rare"},
  {pack:"Rare",idol:"Narin",group:"MEOVV",rarity:"Rare"},
  {pack:"Rare",idol:"Suho",group:"EXO",rarity:"Rare"},
  {pack:"Epic",idol:"Gawon",group:"MEOVV",rarity:"Epic"},
  {pack:"Epic",idol:"Key",group:"SHINee",rarity:"Epic"},
  {pack:"Epic",idol:"Theo",group:"P1Harmony",rarity:"Epic"},
  {pack:"Epic",idol:"Hayoung",group:"fromis_9",rarity:"Epic"},
  {pack:"Epic",idol:"Liz",group:"IVE",rarity:"Epic"},
  {pack:"Epic",idol:"Jennie",group:"BLACKPINK",rarity:"Epic"},
  {pack:"Epic",idol:"Taesan",group:"BOYNEXTDOOR",rarity:"Epic"},
  {pack:"Epic",idol:"Sui",group:"KiiiKiii",rarity:"Epic"},
  {pack:"Epic",idol:"Megan",group:"KATSEYE",rarity:"Epic"},
  {pack:"Epic",idol:"Lee Know",group:"Stray Kids",rarity:"Epic"},
  {pack:"Epic",idol:"Jongho",group:"ATEEZ",rarity:"Epic"},
  {pack:"Epic",idol:"Pharlita",group:"BABYMONSTER",rarity:"Epic"},
  {pack:"Epic",idol:"Beomgyu",group:"TXT",rarity:"Epic"},
  {pack:"Epic",idol:"Sunoo",group:"ENHYPEN",rarity:"Epic"},
  {pack:"Epic",idol:"Sieun",group:"STAYC",rarity:"Epic"},
  {pack:"Epic",idol:"Wonderful Winter",group:"aespa",rarity:"Epic"},
  {pack:"Epic",idol:"Zhang Hao",group:"ZEROBASEONE",rarity:"Epic"},
  {pack:"Epic",idol:"Lay",group:"EXO",rarity:"Epic"},
  {pack:"Epic",idol:"S.Coups",group:"SEVENTEEN",rarity:"Epic"},
  {pack:"Epic",idol:"Harua",group:"&TEAM",rarity:"Epic"},
  {pack:"Legendary",idol:"Jonghyun",group:"SHINee",rarity:"Legendary"},
  {pack:"Legendary",idol:"Yeri",group:"Red Velvet",rarity:"Legendary"},
  {pack:"Legendary",idol:"Nicholas",group:"&TEAM",rarity:"Legendary"},
  {pack:"Legendary",idol:"Shuhua",group:"(G)I-DLE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Gaeul",group:"IVE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Yoon",group:"STAYC",rarity:"Legendary"},
  {pack:"Legendary",idol:"Jongseob",group:"P1Harmony",rarity:"Legendary"},
  {pack:"Legendary",idol:"I.N",group:"Stray Kids",rarity:"Legendary"},
  {pack:"Legendary",idol:"Mina",group:"TWICE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Jo Yuri",group:"IZ*ONE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Jisung",group:"NCT DREAM",rarity:"Legendary"},
  {pack:"Legendary",idol:"Sungchan",group:"RIIZE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Martin",group:"CORTIS",rarity:"Legendary"},
  {pack:"Legendary",idol:"A-na",group:"Hearts2Hearts",rarity:"Legendary"},
  {pack:"Legendary",idol:"Hoony",group:"WINNER",rarity:"Legendary"},
  {pack:"Legendary",idol:"Yunah",group:"ILLIT",rarity:"Legendary"},
  {pack:"Legendary",idol:"Yujin ZB1",group:"ZEROBASEONE",rarity:"Legendary"},
  {pack:"Legendary",idol:"Jin",group:"BTS",rarity:"Legendary"},
  {pack:"Mythic",idol:"Rami",group:"BABYMONSTER",rarity:"Mythic"},
  {pack:"Mythic",idol:"Gyuvin",group:"ZEROBASEONE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Seungmin",group:"Stray Kids",rarity:"Mythic"},
  {pack:"Mythic",idol:"Hongjoong",group:"ATEEZ",rarity:"Mythic"},
  {pack:"Mythic",idol:"Lily",group:"NMIXX",rarity:"Mythic"},
  {pack:"Mythic",idol:"Jun SVT",group:"SEVENTEEN",rarity:"Mythic"},
  {pack:"Mythic",idol:"Chuu",group:"LOONA",rarity:"Mythic"},
  {pack:"Mythic",idol:"Chanyeol",group:"EXO",rarity:"Mythic"},
  {pack:"Mythic",idol:"Jihyo",group:"TWICE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Leesol",group:"KiiiKiii",rarity:"Mythic"},
  {pack:"Mythic",idol:"Manon",group:"KATSEYE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Isa",group:"STAYC",rarity:"Mythic"},
  {pack:"Mythic",idol:"Woonhak",group:"BOYNEXTDOOR",rarity:"Mythic"},
  {pack:"Mythic",idol:"Taehyun",group:"TXT",rarity:"Mythic"},
  {pack:"Mythic",idol:"Jo",group:"&TEAM",rarity:"Mythic"},
  {pack:"Mythic",idol:"Suga",group:"BTS",rarity:"Mythic"},
  {pack:"Mythic",idol:"Doyoung",group:"NCT",rarity:"Mythic"},
  {pack:"Mythic",idol:"Rei",group:"IVE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Ye-on",group:"Hearts2Hearts",rarity:"Mythic"},
  {pack:"Mythic",idol:"Jisun",group:"fromis_9",rarity:"Mythic"},
  {pack:"Mythic",idol:"Iroha",group:"ILLIT",rarity:"Mythic"},
  {pack:"Mythic",idol:"Intak",group:"P1Harmony",rarity:"Mythic"},
  {pack:"Mythic",idol:"Eunseok",group:"RIIZE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Julle",group:"KISS OF LIFE",rarity:"Mythic"},
  {pack:"Mythic",idol:"Onew",group:"SHINee",rarity:"Mythic"},
  {pack:"Mythic",idol:"Ryujin",group:"ITZY",rarity:"Mythic"},
  {pack:"Ethereal",idol:"Maki",group:"&TEAM",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Dino",group:"SEVENTEEN",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Soyeon",group:"(G)I-DLE",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Han",group:"Stray Kids",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jiyu",group:"KiiiKiii",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Hyein",group:"NewJeans",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Minju",group:"ILLIT",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Seulgi",group:"Red Velvet",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Keonho",group:"CORTIS",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jiwoo",group:"Hearts2Hearts",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jaehyun",group:"BOYNEXTDOOR",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Chiquita",group:"BABYMONSTER",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jimin",group:"BTS",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Mino",group:"WINNER",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Daesung",group:"BIGBANG",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jungwon",group:"ENHYPEN",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Jiwon",group:"fromis_9",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Seeun",group:"STAYC",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Joshua",group:"SEVENTEEN",rarity:"Ethereal"},
  {pack:"Ethereal",idol:"Gunwook",group:"ZEROBASEONE",rarity:"Ethereal"},
  {pack:"Secret",idol:"Bae",group:"NMIXX",rarity:"Secret"},
  {pack:"Secret",idol:"Sohee",group:"RIIZE",rarity:"Secret"},
  {pack:"Secret",idol:"Hanbin",group:"TEMPEST",rarity:"Secret"},
  {pack:"Secret",idol:"Natty",group:"KISS OF LIFE",rarity:"Secret"},
  {pack:"Secret",idol:"Sumin",group:"STAYC",rarity:"Secret"},
  {pack:"Secret",idol:"Chen",group:"EXO",rarity:"Secret"},
  {pack:"Secret",idol:"Seonghwa",group:"ATEEZ",rarity:"Secret"},
  {pack:"Secret",idol:"Keeho",group:"P1Harmony",rarity:"Secret"},
  {pack:"Secret",idol:"Yuha",group:"Hearts2Hearts",rarity:"Secret"},
  {pack:"Secret",idol:"Haum",group:"KiiiKiii",rarity:"Secret"},
  {pack:"Secret",idol:"Vernon",group:"SEVENTEEN",rarity:"Secret"},
  {pack:"Secret",idol:"Changbin",group:"Stray Kids",rarity:"Secret"},
  {pack:"Secret",idol:"Jay",group:"ENHYPEN",rarity:"Secret"},
  {pack:"Secret",idol:"Seoyeon",group:"fromis_9",rarity:"Secret"},
  {pack:"Secret",idol:"Yuma",group:"&TEAM",rarity:"Secret"},
  {pack:"Secret",idol:"Soobin",group:"TXT",rarity:"Secret"},
  {pack:"Secret",idol:"Leeseo",group:"IVE",rarity:"Secret"},
  {pack:"Oblivion",idol:"Soobin X Beomgyu",group:"TXT",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"DK",group:"SEVENTEEN",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Yujin",group:"IVE",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Momo",group:"TWICE",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Ana",group:"Hearts2Hearts",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Chenle",group:"NCT DREAM",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Yuqi",group:"(G)I-DLE",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Juun",group:"Hearts2Hearts",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Sooin",group:"MEOVV",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Moka",group:"ILLIT",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Ni-ki",group:"ENHYPEN",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Irene",group:"Red Velvet",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Kyujin",group:"NMIXX",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Ricky",group:"ZEROBASEONE",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Shotaro",group:"RIIZE",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Baekhyun",group:"EXO",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Juhoon",group:"CORTIS",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Eunchae",group:"LE SSERAFIM",rarity:"Oblivion"},
  {pack:"Oblivion",idol:"Fromis Chaeyoung",group:"fromis_9",rarity:"Oblivion"},
  {pack:"Eternal",idol:"Wonhee",group:"ILLIT",rarity:"Eternal"},
  {pack:"Eternal",idol:"Seungkwan",group:"SEVENTEEN",rarity:"Eternal"},
  {pack:"Eternal",idol:"TOP",group:"BIGBANG",rarity:"Eternal"},
  {pack:"Eternal",idol:"Tzuyu",group:"TWICE",rarity:"Eternal"},
  {pack:"Eternal",idol:"Haewon",group:"NMIXX",rarity:"Eternal"},
  {pack:"Eternal",idol:"NingNing",group:"aespa",rarity:"Eternal"},
  {pack:"Eternal",idol:"Yunho",group:"ATEEZ",rarity:"Eternal"},
  {pack:"Eternal",idol:"Danielle",group:"NewJeans",rarity:"Eternal"},
  {pack:"Eternal",idol:"Yoonchae",group:"KATSEYE",rarity:"Eternal"},
  {pack:"Eternal",idol:"Anton",group:"RIIZE",rarity:"Eternal"},
  {pack:"Eternal",idol:"Carmen",group:"Hearts2Hearts",rarity:"Eternal"},
  {pack:"Eternal",idol:"Sana X Momo",group:"TWICE",rarity:"Eternal"},
  {pack:"Eternal",idol:"Hueningkai",group:"TXT",rarity:"Eternal"},
  {pack:"Eternal",idol:"Kazuha",group:"LE SSERAFIM",rarity:"Eternal"},
  {pack:"Eternal",idol:"Taeyeon",group:"Girls' Generation",rarity:"Eternal"},
  {pack:"Eternal",idol:"Haechan",group:"NCT",rarity:"Eternal"},
  {pack:"Eternal",idol:"Woozi",group:"SEVENTEEN",rarity:"Eternal"},
  {pack:"Eternal",idol:"Ahyeon",group:"BABYMONSTER",rarity:"Eternal"},
  {pack:"Transcendent",idol:"Minho",group:"SHINee",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Mark Lee",group:"NCT",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Kai",group:"EXO",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Seonghyeon",group:"CORTIS",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Sakura",group:"LE SSERAFIM",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"KATSEYE",group:"KATSEYE",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Wonwoo",group:"SEVENTEEN",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Taehyung",group:"BTS",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Wendy",group:"Red Velvet",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Wooyoung",group:"ATEEZ",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Red Velvet",group:"Red Velvet",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Wonbin",group:"RIIZE",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Minnie",group:"(G)I-DLE",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Megan X Yoonchae",group:"KATSEYE",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Nayeon",group:"TWICE",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"IU",group:"Solo",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Minji",group:"NewJeans",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"Giselle",group:"aespa",rarity:"Transcendent"},
  {pack:"Transcendent",idol:"HyunJin",group:"LOONA",rarity:"Transcendent"},
  {pack:"Infinity",idol:"Taki",group:"&TEAM",rarity:"Infinity"},
  {pack:"Infinity",idol:"Yeji",group:"ITZY",rarity:"Infinity"},
  {pack:"Infinity",idol:"Sana",group:"TWICE",rarity:"Infinity"},
  {pack:"Infinity",idol:"Saja Boys",group:"Saja Boys",rarity:"Infinity"},
  {pack:"Infinity",idol:"Yena",group:"IZ*ONE",rarity:"Infinity"},
  {pack:"Infinity",idol:"Winter",group:"aespa",rarity:"Infinity"},
  {pack:"Infinity",idol:"ITZY",group:"ITZY",rarity:"Infinity"},
  {pack:"Infinity",idol:"Ella",group:"MEOVV",rarity:"Infinity"},
  {pack:"Infinity",idol:"HUNTR/X",group:"HUNTR/X",rarity:"Infinity"},
  {pack:"Infinity",idol:"Jaehyun NCT",group:"NCT",rarity:"Infinity"},
  {pack:"Infinity",idol:"Joy",group:"Red Velvet",rarity:"Infinity"},
  {pack:"Infinity",idol:"Stella",group:"Hearts2Hearts",rarity:"Infinity"},
  {pack:"Infinity",idol:"Hoshi",group:"SEVENTEEN",rarity:"Infinity"},
  {pack:"Infinity",idol:"D.O.",group:"EXO",rarity:"Infinity"},
  {pack:"Infinity",idol:"BLACKPINK",group:"BLACKPINK",rarity:"Infinity"},
  {pack:"Infinity",idol:"Yunjin",group:"LE SSERAFIM",rarity:"Infinity"},
  {pack:"Infinity",idol:"Mingi",group:"ATEEZ",rarity:"Infinity"},
  {pack:"Infinity",idol:"ILLIT",group:"ILLIT",rarity:"Infinity"},
  {pack:"Infinity",idol:"Bang Chan",group:"Stray Kids",rarity:"Infinity"},
  {pack:"Infinity",idol:"Karina X Giselle",group:"aespa",rarity:"Infinity"},
  {pack:"Infinity",idol:"CORTIS",group:"CORTIS",rarity:"Infinity"},
  {pack:"Infinity",idol:"Enhypen",group:"ENHYPEN",rarity:"Infinity"},
  {pack:"Infinity",idol:"Taehyun X Hueningkai",group:"TXT",rarity:"Infinity"},
  {pack:"Infinity",idol:"Stray Kids",group:"Stray Kids",rarity:"Infinity"},
  {pack:"Infinity",idol:"Sakura X Chaewon",group:"LE SSERAFIM",rarity:"Infinity"},
  {pack:"Infinity",idol:"Heeseung",group:"ENHYPEN",rarity:"Infinity"},
  {pack:"Infinity",idol:"Hanni",group:"NewJeans",rarity:"Infinity"},
  {pack:"Infinity",idol:"J-hope",group:"BTS",rarity:"Infinity"},
  {pack:"Apex",idol:"TWICE",group:"TWICE",rarity:"Apex"},
  {pack:"Apex",idol:"San",group:"ATEEZ",rarity:"Apex"},
  {pack:"Apex",idol:"Ian",group:"Hearts2Hearts",rarity:"Apex"},
  {pack:"Apex",idol:"Myeon",group:"(G)I-DLE",rarity:"Apex"},
  {pack:"Apex",idol:"Felix",group:"Stray Kids",rarity:"Apex"},
  {pack:"Apex",idol:"Yeonjun",group:"TXT",rarity:"Apex"},
  {pack:"Apex",idol:"Jiwoo H2H",group:"Hearts2Hearts",rarity:"Apex"},
  {pack:"Apex",idol:"Karina",group:"aespa",rarity:"Apex"},
  {pack:"Apex",idol:"BTS",group:"BTS",rarity:"Apex"},
  {pack:"Apex",idol:"Haerin",group:"NewJeans",rarity:"Apex"},
  {pack:"Apex",idol:"Asa",group:"BABYMONSTER",rarity:"Apex"},
  {pack:"Apex",idol:"Wonyoung X Liz",group:"IVE",rarity:"Apex"},
  {pack:"Apex",idol:"Sunghoon X Niki",group:"ENHYPEN",rarity:"Apex"},
  {pack:"Apex",idol:"Anna",group:"MEOVV",rarity:"Apex"},
  {pack:"Apex",idol:"Yuna",group:"ITZY",rarity:"Apex"},
  {pack:"Apex",idol:"Sunghoon",group:"ENHYPEN",rarity:"Apex"},
  {pack:"Apex",idol:"Chaewon",group:"LE SSERAFIM",rarity:"Apex"},
  {pack:"Apex",idol:"TXT",group:"TXT",rarity:"Apex"},
  {pack:"Apex",idol:"NewJeans",group:"NewJeans",rarity:"Apex"},
  {pack:"Apex",idol:"Ive",group:"IVE",rarity:"Apex"},
  {pack:"Apex",idol:"Wonyoung",group:"IVE",rarity:"Apex"},
  {pack:"Apex",idol:"Sullyoon",group:"NMIXX",rarity:"Apex"},
  {pack:"Apex",idol:"Le Sserafim",group:"LE SSERAFIM",rarity:"Apex"},
  {pack:"Apex",idol:"ATEEZ",group:"ATEEZ",rarity:"Apex"},
  {pack:"Apex",idol:"Hanni X Danielle",group:"NewJeans",rarity:"Apex"},
  {pack:"Apex",idol:"G-Dragon",group:"BIGBANG",rarity:"Apex"},
  {pack:"Apex",idol:"Jungkook",group:"BTS",rarity:"Apex"},
  {pack:"Fansign",idol:"Fansign Giselle",group:"aespa",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Fuma",group:"&TEAM",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Anna",group:"MEOVV",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Martin",group:"CORTIS",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Haerin",group:"NewJeans",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Jungkook",group:"BTS",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Wonbin",group:"RIIZE",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Keeho",group:"P1Harmony",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Sakura",group:"LE SSERAFIM",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Yuna",group:"ITZY",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign IN",group:"Stray Kids",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Hoshi",group:"SEVENTEEN",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Jay",group:"ENHYPEN",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Wonyoung",group:"IVE",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Yunho",group:"ATEEZ",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Hueningkai",group:"TXT",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Moka",group:"ILLIT",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Ricky",group:"ZEROBASEONE",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Haum",group:"KiiiKiii",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Sullyoon",group:"NMIXX",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Jiwoo",group:"Hearts2Hearts",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Tzuyu",group:"TWICE",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Ahyeon",group:"BABYMONSTER",rarity:"Fansign"},
  {pack:"Fansign",idol:"Fansign Ian",group:"Hearts2Hearts",rarity:"Fansign"},
  {pack:"Vacation",idol:"London Sungchan",group:"RIIZE",rarity:"Vacation"},
  {pack:"Vacation",idol:"French Ella",group:"MEOVV",rarity:"Vacation"},
  {pack:"Vacation",idol:"Beach Moka",group:"ILLIT",rarity:"Vacation"},
  {pack:"Vacation",idol:"Fluffy K",group:"&TEAM",rarity:"Vacation"},
  {pack:"Vacation",idol:"Frosty Kazuha",group:"LE SSERAFIM",rarity:"Vacation"},
  {pack:"Vacation",idol:"Beach Jiung",group:"P1Harmony",rarity:"Vacation"},
  {pack:"Vacation",idol:"Sunset Evan",group:"ENHYPEN",rarity:"Vacation"},
  {pack:"Vacation",idol:"Australian Haum",group:"KiiiKiii",rarity:"Vacation"},
  {pack:"Vacation",idol:"California Ana",group:"Hearts2Hearts",rarity:"Vacation"},
  {pack:"Vacation",idol:"Summer Stella X Yuha",group:"Hearts2Hearts",rarity:"Vacation"},
  {pack:"Vacation",idol:"Lake Jungwon",group:"ENHYPEN",rarity:"Vacation"},
  {pack:"Vacation",idol:"Desert Winwin",group:"NCT / WayV",rarity:"Vacation"},
  {pack:"Concept",idol:"Legendary Lee Know",group:"Stray Kids",rarity:"Concept"},
  {pack:"Concept",idol:"Kingly K",group:"&TEAM",rarity:"Concept"},
  {pack:"Concept",idol:"Jubilant Jaemin",group:"NCT DREAM",rarity:"Concept"},
  {pack:"Concept",idol:"Whiplash Winter",group:"aespa",rarity:"Concept"},
  {pack:"Concept",idol:"Enchanting Eunchae",group:"LE SSERAFIM",rarity:"Concept"},
  {pack:"Concept",idol:"Majestic Mingyu",group:"SEVENTEEN",rarity:"Concept"},
  {pack:"Concept",idol:"Wondrous Wooyoung",group:"ATEEZ",rarity:"Concept"},
  {pack:"Concept",idol:"Luminous Leesol",group:"KiiiKiii",rarity:"Concept"},
  {pack:"Concept",idol:"Smooth Suga",group:"BTS",rarity:"Concept"},
  {pack:"Concept",idol:"Youthful Yeji",group:"ITZY",rarity:"Concept"},
  {pack:"Concept",idol:"Mystic Minji",group:"NewJeans",rarity:"Concept"},
  {pack:"Concept",idol:"Timeless Theo",group:"P1Harmony",rarity:"Concept"},
  {pack:"Concept",idol:"Suave Sunghoon",group:"ENHYPEN",rarity:"Concept"},
  {pack:"Concept",idol:"Serene Sohee",group:"RIIZE",rarity:"Concept"},
  {pack:"Concept",idol:"Iridescent Iroha",group:"ILLIT",rarity:"Concept"},
  {pack:"Concept",idol:"Radiant Rei",group:"IVE",rarity:"Concept"},
  {pack:"Concept",idol:"Captivating Carmen",group:"Hearts2Hearts",rarity:"Concept"},
  {pack:"Concept",idol:"Shimmering Sana",group:"TWICE",rarity:"Concept"},
  {pack:"Concept",idol:"Beaming Beomgyu",group:"TXT",rarity:"Concept"},
  {pack:"Concept",idol:"Jeweled Jisoo",group:"BLACKPINK",rarity:"Concept"},
  {pack:"Concept",idol:"Kinetic Karina",group:"aespa",rarity:"Concept"},
  {pack:"Concept",idol:"Jovial Joy",group:"Red Velvet",rarity:"Concept"},
  {pack:"Concept",idol:"Angelic Ahyeon",group:"BABYMONSTER",rarity:"Concept"},
  {pack:"Concept",idol:"Stellar Stella",group:"Hearts2Hearts",rarity:"Concept"},
  {pack:"Concept",idol:"Heavenly Haewon",group:"NMIXX",rarity:"Concept"},
  {pack:"Performance",idol:"Jawdropping Jisun",group:"fromis_9",rarity:"Performance"},
  {pack:"Performance",idol:"Yearning Yunjin",group:"LE SSERAFIM",rarity:"Performance"},
  {pack:"Performance",idol:"Shining Shotaro",group:"RIIZE",rarity:"Performance"},
  {pack:"Performance",idol:"Jubilant Juun",group:"Hearts2Hearts",rarity:"Performance"},
  {pack:"Performance",idol:"Thunderous Theo",group:"P1Harmony",rarity:"Performance"},
  {pack:"Performance",idol:"Notable NingNing",group:"aespa",rarity:"Performance"},
  {pack:"Performance",idol:"Kinetic K",group:"&TEAM",rarity:"Performance"},
  {pack:"Performance",idol:"Witty Woozi",group:"SEVENTEEN",rarity:"Performance"},
  {pack:"Performance",idol:"Jubilant Jongho",group:"ATEEZ",rarity:"Performance"},
  {pack:"Performance",idol:"Spectacular Sullyoon",group:"NMIXX",rarity:"Performance"},
  {pack:"Performance",idol:"Gallant Gaeul",group:"IVE",rarity:"Performance"},
  {pack:"Performance",idol:"Showtime Sana",group:"TWICE",rarity:"Performance"},
  {pack:"Performance",idol:"Yearning Yuqi",group:"(G)I-DLE",rarity:"Performance"},
  {pack:"Performance",idol:"Astounding Anna",group:"MEOVV",rarity:"Performance"},
  {pack:"Performance",idol:"Knightly Keonho",group:"CORTIS",rarity:"Performance"},
  {pack:"Performance",idol:"Heroic Hanbin",group:"TEMPEST",rarity:"Performance"},
  {pack:"Performance",idol:"Illustrious Irene",group:"Red Velvet",rarity:"Performance"},
  {pack:"Performance",idol:"Dazzling Danielle",group:"NewJeans",rarity:"Performance"},
  {pack:"Performance",idol:"Joyous Jungkook",group:"BTS",rarity:"Performance"},
  {pack:"Performance",idol:"Sensational Soobin",group:"TXT",rarity:"Performance"},
  {pack:"Performance",idol:"Heavenly Hyunjin",group:"Stray Kids",rarity:"Performance"},
  {pack:"Performance",idol:"Commanding Chenle",group:"NCT DREAM",rarity:"Performance"},
  {pack:"Performance",idol:"Wonderful Woonhak",group:"BOYNEXTDOOR",rarity:"Performance"},
  {pack:"Performance",idol:"Nimble Ni-Ki",group:"ENHYPEN",rarity:"Performance"},
  {pack:"Performance",idol:"Yearning Yeji",group:"ITZY",rarity:"Performance"},
  {pack:"Performance",idol:"Mesmerizing Moka",group:"ILLIT",rarity:"Performance"},
  {pack:"Performance",idol:"Starstruck Stella",group:"Hearts2Hearts",rarity:"Performance"},
  {pack:"Iconic",idol:"Dress Up Dohoon",group:"TWS",rarity:"Iconic"},
  {pack:"Iconic",idol:"Debut Jungkook",group:"BTS",rarity:"Iconic"},
  {pack:"Iconic",idol:"Strawberry Wonyoung",group:"IVE",rarity:"Iconic"},
  {pack:"Iconic",idol:"How Sweet Danielle",group:"NewJeans",rarity:"Iconic"},
  {pack:"Iconic",idol:"Pink Hair Giselle",group:"aespa",rarity:"Iconic"},
  {pack:"Iconic",idol:"Churro Felix",group:"Stray Kids",rarity:"Iconic"},
  {pack:"Iconic",idol:"Camo EJ",group:"&TEAM",rarity:"Iconic"},
  {pack:"Iconic",idol:"Swaggy Haum",group:"KiiiKiii",rarity:"Iconic"},
  {pack:"Iconic",idol:"Jolly Jeemin",group:"izna",rarity:"Iconic"},
  {pack:"Iconic",idol:"Winking Gehlee",group:"UNIS",rarity:"Iconic"},
  {pack:"Iconic",idol:"Claw Mingi",group:"ATEEZ",rarity:"Iconic"},
  {pack:"Iconic",idol:"Blonde Stella",group:"Hearts2Hearts",rarity:"Iconic"},
  {pack:"Iconic",idol:"Touring Tzuyu",group:"TWICE",rarity:"Iconic"},
  {pack:"Iconic",idol:"NewJeans Era Haerin",group:"NewJeans",rarity:"Iconic"},
  {pack:"Iconic",idol:"Tuff G-Dragon",group:"BIGBANG",rarity:"Iconic"},
  {pack:"Iconic",idol:"It's Me Minju",group:"ILLIT",rarity:"Iconic"},
  {pack:"Iconic",idol:"Bob Yeji",group:"ITZY",rarity:"Iconic"},
  {pack:"Iconic",idol:"Business Yooyeon",group:"tripleS",rarity:"Iconic"},
  {pack:"Iconic",idol:"Yuzu Yuha",group:"Hearts2Hearts",rarity:"Iconic"},
  {pack:"Fashion",idol:"Stripes Seoyeon",group:"fromis_9",rarity:"Fashion"},
  {pack:"Fashion",idol:"Tracksuit Seungmin",group:"Stray Kids",rarity:"Fashion"},
  {pack:"Fashion",idol:"Hoodie Chiquita",group:"BABYMONSTER",rarity:"Fashion"},
  {pack:"Fashion",idol:"Peace Lily",group:"NMIXX",rarity:"Fashion"},
  {pack:"Fashion",idol:"Swaggy Megan",group:"KATSEYE",rarity:"Fashion"},
  {pack:"Fashion",idol:"Glasses Winwin",group:"NCT / WayV",rarity:"Fashion"},
  {pack:"Fashion",idol:"Y2K Haum",group:"KiiiKiii",rarity:"Fashion"},
  {pack:"Fashion",idol:"Bandana Nayeon",group:"TWICE",rarity:"Fashion"},
  {pack:"Fashion",idol:"Supernatural Danielle",group:"NewJeans",rarity:"Fashion"},
  {pack:"Fashion",idol:"Swaggy Jiung",group:"P1Harmony",rarity:"Fashion"},
  {pack:"Fashion",idol:"Swaggy NingNing",group:"aespa",rarity:"Fashion"},
  {pack:"Fashion",idol:"Winking Minju",group:"ILLIT",rarity:"Fashion"},
  {pack:"Fashion",idol:"Headband Sumin",group:"STAYC",rarity:"Fashion"},
  {pack:"Fashion",idol:"Crochet Rei",group:"IVE",rarity:"Fashion"},
  {pack:"Fashion",idol:"Swaggy K",group:"&TEAM",rarity:"Fashion"},
  {pack:"Fashion",idol:"Football Anna",group:"MEOVV",rarity:"Fashion"},
  {pack:"Fashion",idol:"Beanie Yuqi",group:"(G)I-DLE",rarity:"Fashion"},
  {pack:"Fashion",idol:"Hoodie Yunjin",group:"LE SSERAFIM",rarity:"Fashion"},
  {pack:"Fashion",idol:"Business Soobin",group:"TXT",rarity:"Fashion"},
  {pack:"Fashion",idol:"Glasses Gyuvin",group:"ZEROBASEONE",rarity:"Fashion"},
  {pack:"Fashion",idol:"Knitting Jungkook",group:"BTS",rarity:"Fashion"},
  {pack:"Fashion",idol:"Goggles Jaehyun",group:"BOYNEXTDOOR",rarity:"Fashion"},
  {pack:"Fashion",idol:"Fluffy Joy",group:"Red Velvet",rarity:"Fashion"},
  {pack:"Fashion",idol:"Headband Jungwon",group:"ENHYPEN",rarity:"Fashion"},
  {pack:"Fashion",idol:"Hoodie Hoshi",group:"SEVENTEEN",rarity:"Fashion"},
  {pack:"Fashion",idol:"Gyaru Stella",group:"Hearts2Hearts",rarity:"Fashion"},
  {pack:"Fashion",idol:"Headband Seonghwa",group:"ATEEZ",rarity:"Fashion"},
  {pack:"Fashion",idol:"Cherry Wonbin",group:"RIIZE",rarity:"Fashion"},
  {pack:"Harmony",idol:"Jiwoo X Stella",group:"Hearts2Hearts",rarity:"Harmony"},
  {pack:"Harmony",idol:"Haeun X Yeeun",group:"UNCHILD",rarity:"Harmony"},
  {pack:"Harmony",idol:"Yeji X Lia X Chaeryeong",group:"ITZY",rarity:"Harmony"},
  {pack:"Harmony",idol:"NMIXX",group:"NMIXX",rarity:"Harmony"},
  {pack:"Harmony",idol:"Tourists TXT",group:"TXT",rarity:"Harmony"},
  {pack:"Harmony",idol:"Eunchae X Chaewon",group:"LE SSERAFIM",rarity:"Harmony"},
  {pack:"Harmony",idol:"Soobin X Taehyun",group:"TXT",rarity:"Harmony"},
  {pack:"Harmony",idol:"Felix X Changbin",group:"Stray Kids",rarity:"Harmony"},
  {pack:"Harmony",idol:"Yuha X Jiwoo X Stella",group:"Hearts2Hearts",rarity:"Harmony"},
  {pack:"Harmony",idol:"Karina X Winter",group:"aespa",rarity:"Harmony"},
  {pack:"Harmony",idol:"Sunday Morning ILLIT",group:"ILLIT",rarity:"Harmony"},
  {pack:"Harmony",idol:"KiiiKiii",group:"KiiiKiii",rarity:"Harmony"},
  {pack:"Harmony",idol:"Wonhee X Moka",group:"ILLIT",rarity:"Harmony"},
  {pack:"Harmony",idol:"Yunho X Mingi",group:"ATEEZ",rarity:"Harmony"},
  {pack:"Harmony",idol:"&TEAM",group:"&TEAM",rarity:"Harmony"},
  {pack:"Harmony",idol:"Rei X Sullyoon X Liz",group:"IVE / NMIXX",rarity:"Harmony"},
  {pack:"Harmony",idol:"Woni X Minami",group:"RESCENE",rarity:"Harmony"},
  {pack:"Harmony",idol:"P1Harmony Kaisen",group:"P1Harmony",rarity:"Harmony"},
  {pack:"Harmony",idol:"Debut NewJeans",group:"NewJeans",rarity:"Harmony"},
  {pack:"Harmony",idol:"Happy Happy CORTIS",group:"CORTIS",rarity:"Harmony"},
  {pack:"Munch",idol:"Pizza Yuna",group:"ITZY",rarity:"Munch"},
  {pack:"Munch",idol:"Cake Woonhak",group:"BOYNEXTDOOR",rarity:"Munch"},
  {pack:"Munch",idol:"Cake Joy",group:"Red Velvet",rarity:"Munch"},
  {pack:"Munch",idol:"Apple Juice Taerae",group:"ZEROBASEONE",rarity:"Munch"},
  {pack:"Munch",idol:"Ice Cream Kazuha",group:"LE SSERAFIM",rarity:"Munch"},
  {pack:"Munch",idol:"Ice Cream Sieun",group:"STAYC",rarity:"Munch"},
  {pack:"Munch",idol:"Barbecue Soobin",group:"TXT",rarity:"Munch"},
  {pack:"Munch",idol:"Chocolate Hongjoong",group:"ATEEZ",rarity:"Munch"},
  {pack:"Munch",idol:"Dubai Chewy Cookie Sunoo",group:"ENHYPEN",rarity:"Munch"},
  {pack:"Munch",idol:"Pork Bun Ruka",group:"BABYMONSTER",rarity:"Munch"},
  {pack:"Munch",idol:"Ice Cream Sandwich Wonhee",group:"ILLIT",rarity:"Munch"},
  {pack:"Munch",idol:"Pizza Jiyu",group:"KiiiKiii",rarity:"Munch"},
  {pack:"Munch",idol:"Pizza Jisoo",group:"BLACKPINK",rarity:"Munch"},
  {pack:"Munch",idol:"Ice Cream Yujin",group:"IVE",rarity:"Munch"},
  {pack:"Munch",idol:"Chicken Parm Yoonchae",group:"KATSEYE",rarity:"Munch"},
  {pack:"Munch",idol:"Donut I.N",group:"Stray Kids",rarity:"Munch"},
  {pack:"Munch",idol:"Taiyaki Sullyoon",group:"NMIXX",rarity:"Munch"},
  {pack:"Munch",idol:"Crossaint Minnie",group:"(G)I-DLE",rarity:"Munch"},
  {pack:"Munch",idol:"Donut Nayeon",group:"TWICE",rarity:"Munch"},
  {pack:"Munch",idol:"Noodles Jin",group:"BTS",rarity:"Munch"},
  {pack:"Munch",idol:"Rolled Ice Cream Shotaro",group:"RIIZE",rarity:"Munch"},
  {pack:"Munch",idol:"Pizza DK",group:"SEVENTEEN",rarity:"Munch"},
  {pack:"Munch",idol:"Strawberry Shortcake Winter",group:"aespa",rarity:"Munch"},
  {pack:"Munch",idol:"Pastry Stella",group:"Hearts2Hearts",rarity:"Munch"},
  {pack:"Munch",idol:"Donut Leeseo",group:"IVE",rarity:"Munch"},
  {pack:"Munch",idol:"Pro Chef Jaemin",group:"NCT DREAM",rarity:"Munch"},
  {pack:"Munch",idol:"Baguette Soul",group:"P1Harmony",rarity:"Munch"},
  {pack:"Mirror",idol:"Mirror Taehyung",group:"BTS",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror I.N",group:"Stray Kids",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Ahyeon",group:"BABYMONSTER",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Dahyun",group:"TWICE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Mingi",group:"ATEEZ",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Hayeon",group:"tripleS",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Dohoon",group:"TWS",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Moka",group:"ILLIT",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Sunoo",group:"ENHYPEN",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Kazuha",group:"LE SSERAFIM",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Wendy",group:"Red Velvet",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Haewon",group:"NMIXX",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Hinata",group:"XG",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Keeho",group:"P1Harmony",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Gaeul",group:"IVE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Juhoon",group:"CORTIS",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Baekhyun",group:"EXO",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Yeonjun",group:"TXT",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Haechan",group:"NCT 127",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Wonbin",group:"RIIZE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Taesan",group:"BOYNEXTDOOR",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Jisoo",group:"BLACKPINK",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Miyeon",group:"(G)I-DLE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Nagyung",group:"fromis_9",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Minji",group:"NewJeans",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Giselle",group:"aespa",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Leesol",group:"KiiiKiii",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Ella",group:"MEOVV",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Harua",group:"&TEAM",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Lia",group:"ITZY",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Jiwoo X Juun",group:"Hearts2Hearts",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Taerae",group:"ZEROBASEONE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Megan",group:"KATSEYE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Zena",group:"RESCENE",rarity:"Mirror"},
  {pack:"Mirror",idol:"Mirror Yoon",group:"STAYC",rarity:"Mirror"},
  {pack:"Cutesy",idol:"Cutesy Yuha",group:"Hearts2Hearts",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Zena",group:"RESCENE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Jiwoong",group:"ZEROBASEONE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Mingi",group:"ATEEZ",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Intak",group:"P1Harmony",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Yujin",group:"IVE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Hueningkai",group:"TXT",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Bangchan",group:"Stray Kids",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Kai",group:"EXO",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Evan",group:"Solo",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Miyeon",group:"(G)I-DLE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Jun",group:"SEVENTEEN",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Kya",group:"KiiiKiii",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Ella",group:"MEOVV",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Karina",group:"aespa",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Hyein",group:"NewJeans",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Seeun",group:"STAYC",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Chuu",group:"Solo",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Hayoung",group:"fromis_9",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Chaeryeong",group:"ITZY",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Dahyun",group:"TWICE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Hayeon",group:"tripleS",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Youngjae",group:"TWS",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Yena",group:"Solo",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Shotaro",group:"RIIZE",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Jimin",group:"BTS",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Woonhak",group:"BOYNEXTDOOR",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Chaewon",group:"LE SSERAFIM",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Wonhee",group:"ILLIT",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Rora",group:"BABYMONSTER",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Jungeun",group:"izna",rarity:"Cutesy"},
  {pack:"Cutesy",idol:"Cutesy Sullyoon",group:"NMIXX",rarity:"Cutesy"},
  {pack:"Pets",idol:"Chaewon X Shiro",group:"LE SSERAFIM",rarity:"Pets"},
  {pack:"Pets",idol:"Kitty Ten",group:"WayV",rarity:"Pets"},
  {pack:"Pets",idol:"Puppy Yeojin",group:"LOONA",rarity:"Pets"},
  {pack:"Pets",idol:"Shlawg Keonho",group:"CORTIS",rarity:"Pets"},
  {pack:"Pets",idol:"Dawgy Leehan",group:"BOYNEXTDOOR",rarity:"Pets"},
  {pack:"Pets",idol:"Dawg Yunah",group:"ILLIT",rarity:"Pets"},
  {pack:"Pets",idol:"Samoyed Jeno",group:"NCT DREAM",rarity:"Pets"},
  {pack:"Pets",idol:"Dawg Mai",group:"izna",rarity:"Pets"},
  {pack:"Pets",idol:"Happy Doggo Felix",group:"Stray Kids",rarity:"Pets"},
  {pack:"Pets",idol:"J-Hope X Mickey",group:"BTS",rarity:"Pets"},
  {pack:"Pets",idol:"Puppy Wonbin",group:"RIIZE",rarity:"Pets"},
  {pack:"Pets",idol:"Rose X Hank",group:"BLACKPINK",rarity:"Pets"},
  {pack:"Pets",idol:"Parakeet Beomgyu",group:"TXT",rarity:"Pets"},
  {pack:"Pets",idol:"Dog Maki",group:"&TEAM",rarity:"Pets"},
  {pack:"Pets",idol:"Puppy Gyuvin",group:"ZEROBASEONE",rarity:"Pets"},
  {pack:"Pets",idol:"Shlawg Rei",group:"IVE",rarity:"Pets"},
  {pack:"Pets",idol:"Doggo Giselle",group:"aespa",rarity:"Pets"},
  {pack:"Pets",idol:"Cat Seeun",group:"STAYC",rarity:"Pets"},
  {pack:"Pets",idol:"Puppy Haerin",group:"NewJeans",rarity:"Pets"},
  {pack:"Pets",idol:"Doggo Nayeon",group:"TWICE",rarity:"Pets"},
  {pack:"Pets",idol:"Puppy Jiwoo",group:"Hearts2Hearts",rarity:"Pets"},
  {pack:"Formal",idol:"Formal Jay",group:"ENHYPEN",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Jiyu",group:"KiiiKiii",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Jaehee",group:"NCT WISH",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Wonhee",group:"ILLIT",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Yuna",group:"ITZY",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Yunjin",group:"LE SSERAFIM",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Jiung",group:"P1Harmony",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Gaeul",group:"IVE",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Kai",group:"EXO",rarity:"Formal"},
  {pack:"Formal",idol:"Formal James",group:"CORTIS",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Riwoo",group:"BOYNEXTDOOR",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Nien",group:"tripleS",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Yoon",group:"STAYC",rarity:"Formal"},
  {pack:"Formal",idol:"Formal San",group:"ATEEZ",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Changbin",group:"Stray Kids",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Taerae",group:"ZEROBASEONE",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Jeemin",group:"izna",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Ruka",group:"BABYMONSTER",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Zena",group:"RESCENE",rarity:"Formal"},
  {pack:"Formal",idol:"Formal Ana",group:"Hearts2Hearts",rarity:"Formal"},
  {pack:"Plushie",idol:"Plushie Ian",group:"Hearts2Hearts",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Shotaro",group:"RIIZE",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Hanbin",group:"ZEROBASEONE",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Beomgyu",group:"TXT",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Liz",group:"IVE",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie EJ",group:"&TEAM",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Seungmin",group:"Stray Kids",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Youngjae",group:"TWS",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie J",group:"STAYC",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Sungho",group:"BOYNEXTDOOR",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Sui",group:"KiiiKiii",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Iroha",group:"ILLIT",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Karina",group:"aespa",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Evan",group:"Solo",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie San",group:"ATEEZ",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Chaeyeon",group:"Solo",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Sana",group:"TWICE",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Irene",group:"Red Velvet",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Yewon",group:"FIFTY FIFTY",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Yeji",group:"ITZY",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Hanni",group:"NewJeans",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Anna",group:"MEOVV",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Jaehee",group:"NCT WISH",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Sakura",group:"LE SSERAFIM",rarity:"Plushie"},
  {pack:"Plushie",idol:"Plushie Rora",group:"BABYMONSTER",rarity:"Plushie"},
  {pack:"Event",idol:"Apple Leesol",group:"KiiiKiii",rarity:"Event"},
  {pack:"Event",idol:"Aquatic Sumin",group:"STAYC",rarity:"Event"},
  {pack:"Event",idol:"Sunlit Sunwoo",group:"THE BOYZ",rarity:"Event"},
  {pack:"Event",idol:"Pocari Iroha",group:"ILLIT",rarity:"Event"},
  {pack:"Event",idol:"Balmy Yujin",group:"IVE",rarity:"Event"},
  {pack:"Event",idol:"Warm Jihoon",group:"TWS",rarity:"Event"},
  {pack:"Event",idol:"Dewy Jiwoo",group:"Hearts2Hearts",rarity:"Event"},
  {pack:"Event",idol:"Sunsoaked Haum",group:"KiiiKiii",rarity:"Event"},
  {pack:"Event",idol:"Oceanic I.N",group:"Stray Kids",rarity:"Event"},
  {pack:"Event",idol:"Tropical Winter",group:"aespa",rarity:"Event"},
  {pack:"Event",idol:"Breezy Joonie",group:"ICHILLIN'",rarity:"Event"},
  {pack:"Event",idol:"Sandy Mingi",group:"ATEEZ",rarity:"Event"},
  {pack:"Event",idol:"Summery Chuu",group:"Solo",rarity:"Event"},
  {pack:"Event",idol:"Solar Yeonjun X Taehyun",group:"TXT",rarity:"Event"},
  {pack:"Event",idol:"Coral Belle",group:"KISS OF LIFE",rarity:"Event"},
  {pack:"Event",idol:"Coastal Carmen",group:"Hearts2Hearts",rarity:"Event"},
  {pack:"Event",idol:"Glowing Danielle",group:"NewJeans",rarity:"Event"},
  {pack:"Event",idol:"Salty Youngjae",group:"TWS",rarity:"Event"},
  {pack:"Event",idol:"Marine Jacob",group:"THE BOYZ",rarity:"Event"},
  {pack:"Event",idol:"Sunkissed Gaeul",group:"IVE",rarity:"Event"},
  {pack:"Event",idol:"Beachy Eunchae",group:"LE SSERAFIM",rarity:"Event"},
  {pack:"Visual",idol:"Visual Wonyoung",group:"IVE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Heejin",group:"ARTMS",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Tzuyu",group:"TWICE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Yoona",group:"Girls' Generation",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Miyeon",group:"(G)I-DLE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Haerin",group:"NewJeans",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Minju",group:"ILLIT",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Sunghoon",group:"ENHYPEN",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Xiaoting",group:"Kep1er",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Cha Eun-woo",group:"ASTRO",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Jiwoong",group:"ZEROBASEONE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Pharita",group:"BABYMONSTER",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Manon",group:"KATSEYE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Sullyoon",group:"NMIXX",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Anna",group:"MEOVV",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Juyeon",group:"THE BOYZ",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Jaehyun",group:"BOYNEXTDOOR",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Wonbin",group:"RIIZE",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Hyunjin",group:"Stray Kids",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Irene",group:"Red Velvet",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Yuna",group:"ITZY",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Karina",group:"aespa",rarity:"Visual"},
  {pack:"Visual",idol:"Visual Mingyu",group:"SEVENTEEN",rarity:"Visual"},
  {pack:"Maknae",idol:"Maknae Athena",group:"FIFTY FIFTY",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Jungkook",group:"BTS",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yujin",group:"ZEROBASEONE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Keonho",group:"CORTIS",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Haechan",group:"NCT 127",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Seowon",group:"UNIS",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae I.N",group:"Stray Kids",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Louis",group:"LNGSHOT",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Jongho",group:"ATEEZ",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae J",group:"STAYC",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Ella",group:"MEOVV",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Shuhua",group:"(G)I-DLE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Leeseo",group:"IVE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yuna",group:"ITZY",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Tzuyu",group:"TWICE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Dino",group:"SEVENTEEN",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Donghyeon",group:"KickFlip",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yoonchae",group:"KATSEYE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Jongseob",group:"P1Harmony",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Eric",group:"THE BOYZ",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Cocona",group:"XG",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Maki",group:"&TEAM",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Iroha",group:"ILLIT",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Taemin",group:"SHINee",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yechan",group:"xikers",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Ni-ki",group:"ENHYPEN",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Kyujin",group:"NMIXX",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Zena",group:"RESCENE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Jisung",group:"NCT DREAM",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Daesung",group:"BIGBANG",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Seoah",group:"tripleS",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Woonhak",group:"BOYNEXTDOOR",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Bahiyyih",group:"Kep1er",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Ye-on",group:"Hearts2Hearts",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Huening Kai",group:"TXT",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yangyang",group:"WayV",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Sehun",group:"EXO",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Saebi",group:"izna",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Hyein",group:"NewJeans",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Haneul",group:"KISS OF LIFE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Eunchae",group:"LE SSERAFIM",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Kyungmin",group:"TWS",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Ningning",group:"aespa",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Chiquita",group:"BABYMONSTER",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Anton",group:"RIIZE",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Lisa",group:"BLACKPINK",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Yeri",group:"Red Velvet",rarity:"Maknae"},
  {pack:"Maknae",idol:"Maknae Jun",group:"U-KISS",rarity:"Maknae"},
  {pack:"Leader",idol:"Leader Jihyo",group:"TWICE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jiyu",group:"KiiiKiii",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Yeji",group:"ITZY",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Suho",group:"EXO",rarity:"Leader"},
  {pack:"Leader",idol:"Leader RM",group:"BTS",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sion",group:"NCT WISH",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jihoon",group:"TREASURE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jaehyun",group:"BOYNEXTDOOR",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jungwon",group:"ENHYPEN",rarity:"Leader"},
  {pack:"Leader",idol:"Leader G-Dragon",group:"BIGBANG",rarity:"Leader"},
  {pack:"Leader",idol:"Leader HaSeul",group:"ARTMS",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Minjae",group:"xikers",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Keeho",group:"P1Harmony",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Yunah",group:"ILLIT",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sihyeon",group:"EVERGLOW",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Soobin",group:"TXT",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Haewon",group:"NMIXX",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Moon Sua",group:"Billlie",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sangyeon",group:"THE BOYZ",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Irene",group:"Red Velvet",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Saerom",group:"fromis_9",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Kyehoon",group:"KickFlip",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Chaewon",group:"LE SSERAFIM",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Shownu",group:"MONSTA X",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sumin",group:"STAYC",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sung Hanbin",group:"ZEROBASEONE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jiwoo H2H",group:"Hearts2Hearts",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Mai",group:"izna",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Karina",group:"aespa",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Ohyul",group:"LNGSHOT",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Solar",group:"MAMAMOO",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Yujin IVE",group:"IVE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Seohee",group:"TUIDE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Jurin",group:"XG",rarity:"Leader"},
  {pack:"Leader",idol:"Leader JIU",group:"Dreamcatcher",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Hyunsuk",group:"TREASURE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Kun",group:"WayV",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Yujin Kep1er",group:"Kep1er",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Taeyeon",group:"Girls' Generation",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Onew",group:"SHINee",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Exy",group:"WJSN",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sowon",group:"GFRIEND",rarity:"Leader"},
  {pack:"Leader",idol:"Leader JinJin",group:"ASTRO",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Keena",group:"FIFTY FIFTY",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Soyeon",group:"(G)I-DLE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Taeyong",group:"NCT 127",rarity:"Leader"},
  {pack:"Leader",idol:"Leader EJ",group:"&TEAM",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Shinyu",group:"TWS",rarity:"Leader"},
  {pack:"Leader",idol:"Leader S.Coups",group:"SEVENTEEN",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Martin",group:"CORTIS",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Sophia",group:"KATSEYE",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Hongjoong",group:"ATEEZ",rarity:"Leader"},
  {pack:"Leader",idol:"Leader Bang Chan",group:"Stray Kids",rarity:"Leader"},
  {pack:"Center",idol:"Center Nayeon",group:"TWICE",rarity:"Center"},
  {pack:"Center",idol:"Center Ahyeon",group:"BABYMONSTER",rarity:"Center"},
  {pack:"Center",idol:"Center Jiyu",group:"KiiiKiii",rarity:"Center"},
  {pack:"Center",idol:"Center Kai",group:"EXO",rarity:"Center"},
  {pack:"Center",idol:"Center Shinyu",group:"TWS",rarity:"Center"},
  {pack:"Center",idol:"Center Sung Hanbin",group:"ZEROBASEONE",rarity:"Center"},
  {pack:"Center",idol:"Center Evan",group:"Solo",rarity:"Center"},
  {pack:"Center",idol:"Center Hoshi",group:"SEVENTEEN",rarity:"Center"},
  {pack:"Center",idol:"Center Soyeon",group:"(G)I-DLE",rarity:"Center"},
  {pack:"Center",idol:"Center Taemin",group:"SHINee",rarity:"Center"},
  {pack:"Center",idol:"Center Ian",group:"Hearts2Hearts",rarity:"Center"},
  {pack:"Center",idol:"Center G-Dragon",group:"BIGBANG",rarity:"Center"},
  {pack:"Center",idol:"Center Wonhee",group:"ILLIT",rarity:"Center"},
  {pack:"Center",idol:"Center Yeonjun",group:"TXT",rarity:"Center"},
  {pack:"Center",idol:"Center Haewon",group:"NMIXX",rarity:"Center"},
  {pack:"Center",idol:"Center Jungkook",group:"BTS",rarity:"Center"},
  {pack:"Center",idol:"Center Taeyong",group:"NCT 127",rarity:"Center"},
  {pack:"Center",idol:"Center Jaehyun",group:"BOYNEXTDOOR",rarity:"Center"},
  {pack:"Center",idol:"Center Jeemin",group:"izna",rarity:"Center"},
  {pack:"Center",idol:"Center Chaewon",group:"LE SSERAFIM",rarity:"Center"},
  {pack:"Airport",idol:"Airport Minnie",group:"(G)I-DLE",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Stella",group:"Hearts2Hearts",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Ruka",group:"BABYMONSTER",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Moka",group:"ILLIT",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Giselle",group:"aespa",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Ni-ki",group:"ENHYPEN",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Felix",group:"Stray Kids",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Rei",group:"IVE",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Jennie",group:"BLACKPINK",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Sana",group:"TWICE",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Kazuha",group:"LE SSERAFIM",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Yeonjun",group:"TXT",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Hanni",group:"NewJeans",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Sakura",group:"LE SSERAFIM",rarity:"Airport"},
  {pack:"Airport",idol:"Airport Jake",group:"ENHYPEN",rarity:"Airport"},
  {pack:"Vocal",idol:"Vocal Lily",group:"NMIXX",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal DK",group:"SEVENTEEN",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Miyeon",group:"(G)I-DLE",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Keeho",group:"P1Harmony",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Jongho",group:"ATEEZ",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Wendy",group:"Red Velvet",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Evan",group:"Solo",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Seungmin",group:"Stray Kids",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Sieun",group:"STAYC",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Rami",group:"BABYMONSTER",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Yunjin",group:"LE SSERAFIM",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Baekhyun",group:"EXO",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Sung Hanbin",group:"ZEROBASEONE",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Taeyeon",group:"Girls' Generation",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Liz",group:"IVE",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Ningning",group:"aespa",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Chaehyun",group:"Kep1er",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Taehyun",group:"TXT",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Rosé",group:"BLACKPINK",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Jihyo",group:"TWICE",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Haewon",group:"NMIXX",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Belle",group:"KISS OF LIFE",rarity:"Vocal"},
  {pack:"Vocal",idol:"Vocal Sohee",group:"RIIZE",rarity:"Vocal"}
];
const grades=[["F",1],["E",1.1],["D",1.2],["C",1.3],["B",1.4],["A",1.5],["S",1.6],["X",1.8],["SS",1.9],["XX",2]];
const recipes=[
  [["Radiant","Blazing"],"Sunburst"],[["Iceborn","Moonlit"],"Aurora"],[["Corrupted","Abyssal"],"Void"],
  [["Candy","Crimson"],"Velvet"],[["Abyssal","Corrupted"],"Glitched"],[["Candy","Iceborn"],"Cherished"],
  [["Radiant","Blazing","Corrupted"],"Eclipse"],[["Iceborn","Moonlit","Corrupted"],"Pixelated"],
  [["Radiant","Moonlit","Crimson"],"Blossom"],[["Abyssal","Blazing","Moonlit"],"Cosmic"],
  [["Void","Crimson","Glitched"],"Hollow"],[["Moonlit","Blossom","Radiant"],"Starlight"]
];
const colors={Radiant:"radiant",Blazing:"blazing",Iceborn:"iceborn",Moonlit:"moonlit",Corrupted:"corrupted",Abyssal:"abyssal",Candy:"candy",Crimson:"crimson"};
const mutationColors={
  "Normal / Base":["#e5e7eb","#172033"],Radiant:["#ffffff","#111827"],Sunburst:["#f59e0b","#2b1700"],
  Blazing:["#ef2b2d","#ffffff"],Corrupted:["#7c3aed","#ffffff"],Iceborn:["#9bdcf5","#123047"],
  Moonlit:["#f5d547","#3b2f00"],Aurora:["#6ee7c7","#073b35"],Void:["#4c1d95","#ffffff"],
  Summer:["#eab83e","#3a2500"],Abyssal:["#173b7a","#ffffff"],Candy:["#ec72cf","#3b1232"],
  Cherished:["#d89aac","#32131d"],Crimson:["#a9152a","#ffffff"],Glitched:["#62b36f","#102b14"],
  Velvet:["#cf3f78","#ffffff"],Pixelated:["#7567c9","#ffffff"],Blossom:["#dda4d4","#35142f"],
  Eclipse:["#d66f32","#2c1205"],Cosmic:["#4296ad","#071f29"],Hollow:["#4b445c","#ffffff"],
  Starlight:["#f1c75b","#332500"]
};
